name: Issue Assignment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Assign Issue
      uses: actions/github-script@v7
      with:
        script: |
          const commentBody = github.event.comment.body;
          const validAssignees = process.env.VALID_ASSIGNEES.split(','); // Load valid users from secrets
          
          // Regex to match the command format /assign @username
          const assignRegex = /\/assign\s+(@[\w-]+)/g;
          let match;
          const assignees = [];

          while ((match = assignRegex.exec(commentBody)) !== null) {
            const username = match[1].replace('@', '');
            if (validAssignees.includes(username)) {
              assignees.push(username);
            }
          }
          
          if (assignees.length > 0) {
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: github.event.issue.number,
              assignees: assignees
            });
            console.log(`Assigned issue ${github.event.issue.number} to ${assignees.join(', ')}`);
          } else {
            console.log('No valid assignees found in the comment.');
          }
      env:
        VALID_ASSIGNEES: ${{ secrets.VALID_ASSIGNEES }}
