name: Auto-Assign
on:
  issue_comment:
    types: [created]

jobs:
  assign-users:
    runs-on: ubuntu-latest
    steps:
      - name: Parse and Assign Users
        uses: actions/github-script@v6
        with:
          script: |
            const authorizedUsers = process.env.ASSIGNABLE_USERS.split(',');
            const commentBody = context.payload.comment.body;
            const regex = /\/assign\s+@(\w+)/g;
            let match;
            const assignees = [];

            while ((match = regex.exec(commentBody)) !== null) {
              const username = match[1];
              if (authorizedUsers.includes(username)) {
                assignees.push(username);
              }
            }

            if (assignees.length > 0) {
              await github.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: assignees
              });
            }
        env:
          ASSIGNABLE_USERS: ${{ secrets.ASSIGNABLE_USERS }}
