name: Issue Assignment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Assign Issue
      uses: actions/github-script@v6
      with:
        script: |
          // Debug: Log the entire github.event object
          console.log('Full github.event:', JSON.stringify(github.event, null, 2));
          
          // Check if the event contains the expected properties
          if (!github.event || !github.event.issue || !github.event.number) {
            console.error('Invalid event data');
            return;
          }
          
          // Debug: Log the relevant parts of the event
          console.log('Issue number:', github.event.number);
          console.log('Comment body:', github.event.body?.comment?.body ?? '');
          
          // Rest of the logic remains the same
          const commentBody = github.event.body?.comment?.body ?? '';
          
          // Check if "/assign" is in a separate line
          const lines = commentBody.split('\n');
          const assignLineIndex = lines.findIndex(line => line.trim() === '/assign');
          
          if (assignLineIndex !== -1 && assignLineIndex < lines.length - 1) {
            const assignee = lines[assignLineIndex + 1].trim();
            
            // Assign the issue to the user
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: github.event.number,
              assignees: [assignee]
            });
            
            console.log(`Issue ${github.event.number} assigned to ${assignee}`);
          } else {
            console.log('No valid /assign found in the comment');
          }
