name: Auto Assign Issues

on:
  issue_comment:
    types: [created]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check if commenter is authorized
        id: auth-check
        env:
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
        run: |
          IFS=',' read -r -a authorized_users <<< "$AUTHORIZED_USERS"
          user_authorized=false
          for maintainer in "${authorized_users[@]}"; do
            if [[ "$maintainer" == "${{ github.event.comment.user.login }}" ]]; then
              user_authorized=true
              break
            fi
          done
          if [[ "$user_authorized" == "false" ]]; then
            echo "User is not authorized to assign users."
            exit 1
          fi
        shell: bash

      - name: Assign Users Automatically
        if: steps.auth-check.outcome == 'success'
        uses: OWASP-BLT/BLT-Action@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
