name: Issue Assignment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
    - name: Assign Issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          async function checkUserExists(username) {
            try {
              await github.rest.users.getByUsername({ username });
              return true;
            } catch (error) {
              if (error.status === 404) {
                return false;
              }
              throw error;
            }
          }

          async function hasRepoAccess(username) {
            try {
              const response = await github.rest.repos.checkCollaborator({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: username
              });
              return response.status === 204;
            } catch (error) {
              return false;
            }
          }

          const issueNumber = context.payload.issue.number;
          const commentBody = context.payload.comment.body;
          const commentAuthor = context.payload.comment.user.login;
          
          // Parse the assign command
          const assignRegex = /^\/assign\s+(@[\w-]+\s*)+$/m;
          const match = commentBody.match(assignRegex);
          
          if (match) {
            // Extract usernames (removing @ symbol)
            const assignees = [...commentBody.matchAll(/@([\w-]+)/g)]
              .map(match => match[1]);
            
            if (assignees.length > 0) {
              for (const assignee of assignees) {
                try {
                  // Check if user exists
                  const userExists = await checkUserExists(assignee);
                  if (!userExists) {
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issueNumber,
                      body: `❌ Cannot assign to @${assignee}: User does not exist on GitHub`
                    });
                    continue;
                  }

                  // Check if user has repository access
                  const hasAccess = await hasRepoAccess(assignee);
                  if (!hasAccess) {
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issueNumber,
                      body: `❌ Cannot assign to @${assignee}: User needs to be a repository collaborator`
                    });
                    continue;
                  }

                  // Try to assign the user
                  await github.rest.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    assignees: [assignee]
                  });

                  // Verify the assignment
                  const updatedIssue = await github.rest.issues.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber
                  });

                  const isAssigned = updatedIssue.data.assignees.some(
                    a => a.login.toLowerCase() === assignee.toLowerCase()
                  );

                  if (isAssigned) {
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issueNumber,
                      body: `✅ Successfully assigned to @${assignee}`
                    });
                  } else {
                    throw new Error('Assignment verification failed');
                  }

                } catch (error) {
                  console.error(`Error processing assignment for ${assignee}:`, error);
                  let errorMessage = 'An unexpected error occurred';
                  
                  if (error.status === 403) {
                    errorMessage = 'Insufficient permissions to assign this user';
                  } else if (error.status === 404) {
                    errorMessage = 'User not found';
                  }

                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    body: `❌ Failed to assign @${assignee}: ${errorMessage}`
                  });
                }
              }
            }
          }
