name: Auto Assign Issues

on:
  issue_comment:
    types: [created]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Users Automatically
        uses: OWASP-BLT/BLT-Action@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
