name: Structure Check

on: [push, pull_request]

jobs:
  structure-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set working directory
      run: cd src/scribe_data/check

    - name: Debugging - List contents of src/scribe_data
      run: ls -R ../

    - name: Run check_project_structure.py
      run: python check_project_structure.py

    - name: Post-run status
      if: failure()
      run: echo "Check failed. Please fix the errors."
 