name: Check in on Issues and PRs

on:
  schedule:
    - cron: "*/6 * * * *" # Runs every 6 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  check-in-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check in on issues and PRs
        uses: andrewtavis/check-in-bot@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-inactive: 1 # You can adjust this number
          comment-message: |
            Hello to the maintainers and watchers!

            There have been no updates here for the last two weeks. There might be need for a check in :)

            Thanks and hope all are well! ❤️
