name: Structure Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  structure-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debugging - Confirm structure and paths
      run: |
        echo "Listing directory structure from the root:"
        ls -R .
        echo "Current working directory: $(pwd)"

    - name: Run check_project_structure.py
      working-directory: ./src/scribe_data/check
      run: python check_project_structure.py

    - name: Post-run status
      if: failure()
      run: echo "Check failed. Please fix the errors."
