# check_in_bot.yaml
name: Check in on Issues and PRs

on:
  schedule:
    - cron: "*/6 * * * *" # Runs every 6 minutes

jobs:
  check-in-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check in on issues and PRs
        uses: andrewtavis/check-in-bot@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-inactive: 14
          comment-message: |
            Hello to the maintainers and watchers!

            There have been no updates here for the last two weeks. There might be need for a check in :)

            Thanks and hope all are well! ❤️