name: Notify Matrix Channel of Test Message

on:
  schedule:
    - cron: '30 10 * * 3'  # Every Wednesday at 10:30 UTC
  workflow_dispatch:  # Allows manual triggering

env:
  FIRST_RUN_DATE: "2023-09-30"  # Set the first Wednesday you want this to run

jobs:
  weekindex:
    runs-on: ubuntu-latest
    outputs:
      weekindex: ${{ steps.calculate.outputs.weekindex }}
    steps:
      - name: Calculate week difference
        id: calculate
        run: |
          echo "FIRST_RUN_DATE=${{ env.FIRST_RUN_DATE }}" >> $GITHUB_STEP_SUMMARY
          echo "current_date=$(date +%Y-%m-%d)" >> $GITHUB_STEP_SUMMARY
          echo "weekdiff=$((($(date -d "$current_date" +%s) - $(date -d "${{ env.FIRST_RUN_DATE }}" +%s)) / 60 / 60 / 24 / 7))" >> $GITHUB_STEP_SUMMARY
          echo "weekindex=$((($weekdiff % 2)))" >> $GITHUB_STEP_SUMMARY
          echo "It's the first week of the bi-weekly cycle. The action is going to run." >> $GITHUB_STEP_SUMMARY

  send-message:
    if: ${{ needs.weekindex.outputs.weekindex == '0' }}
    runs-on: ubuntu-latest
    needs:
      - weekindex
    steps:
      - name: Format EPOCH time
        id: epoch-time
        run: |
          echo "EPOCH_TIME=$(date +%s)" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Send message to Matrix channel
        id: matrix-chat-message
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.org'
          token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          channel: ${{ secrets.MATRIX_ROOM_ID }}
          message: |
            Hey all! 🤖👋 Here's the reminder for [this Saturday's dev sync at 16:00 UTC](https://zonestamp.toolforge.org/${{ env.EPOCH_TIME }}) 🤝♻️

            **Details**:
            - Call link: https://call.element.io/room/#/activist-dev-sync?roomId=!UddhHUSXxHAoAnImXb:call.ems.host&password=ASriEQCG4DE6Q1QSB313zig0bhLd62RN
            - This week’s pad: https://etherpad.wikimedia.org/p/activist-dev-sync-${{ env.CURRENT_DATE }}
            - All pads: https://etherpad.wikimedia.org/p/activist-dev-sync

            Please reply with anything you'd like to discuss 🧕🏼‍♀️

            Thanks and have a great day! ❤️0s
