name: Close Pull Request

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Send message to Matrix bots channel
        id: matrix-chat-message
        uses: fadenb/matrix-chat-message@v0.0.6
        env:
          MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
        with:
          homeserver: 'matrix.org'
          channel: '!uyCZZrXQONmiNXjDGx:matrix.org'
          message: |
            new ovos-audio-gelkniujkbiujbiubiubiubii
          messagetype: m.notice
        run: echo "Sending message to Matrix..."
        
      - name: Check Matrix response
        run: |
          if [ $? -ne 0 ]; then
            echo "Error sending message to Matrix:"
            cat matrix-chat-message.log
            exit 1
          fi
