name: Notify Matrix channel of Test Message

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:  

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send test message via Matrix
    steps:
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: |
          🚨 TEST MESSAGE 🚨
          Sent at: $(date +"%Y-%m-%d %H:%M:%S")
          Triggered by: GitHub Actions cron job

    - name: Stop the job
      run: |
        if [ $((GITHUB_RUN_NUMBER % 60)) -eq 0 ]; then
          exit 0
        fi
