name: Notify Matrix channel of Test Message

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send test message via Matrix
    steps:
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: |
          🚨 TEST MESSAGE 🚨
          Sent at: $(date +"%Y-%m-%d %H:%M:%S")
          Triggered by: GitHub Actions cron job

# To stop the job after running once per hour, add this step:
    - name: Stop the job
      if: env.GITHUB_JOB == 'send-message' && env.GITHUB_RUN_NUMBER % 60 == 0
      run: exit 0
