name: Notify Matrix Channel of Test Message

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send test message via Matrix
    steps:
    - name: Format EPOCH time
      id: epoch-time
      run: echo "EPOCH_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: |
          Hey all! 🤖👋 Here's the reminder for [this Saturday's dev sync at 16:00 UTC](https://zonestamp.toolforge.org/${{ env.EPOCH_TIME }}) 🧑‍💻♻️

          Details for it:

          - Call link: https://call.element.io/room/#/activist-dev-sync?roomId=!UddhHUSXxHAoAnImXb:call.ems.host&password=ASriEQCG4DE6Q1QSB313zig0bhLd62RN
          - Pad for this week: https://etherpad.wikimedia.org/p/activist-dev-sync-$(date +%Y-%m-%d)
          - All dev sync pads: https://etherpad.wikimedia.org/p/activist-dev-sync

          Please reply in the thread for this message with anything you'd like to discuss 🧵

          Thanks and have a great day! ❤️

    - name: Stop the job after every 60th run
      run: |
        if [ $((GITHUB_RUN_NUMBER % 60)) -eq 0 ]; then
          exit 0
        fi
