name: CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 2 * * *'  # Run once per day
  workflow_dispatch:

jobs:
  unciv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Demo Test: Add text file to the repository and commit to a new branch
      - name: Create demo test file and commit
        run: |
          echo "This is a demo test for the GitHub Action!" > demo_test.txt
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git checkout -b demo-test-branch
          git add demo_test.txt
          git commit -m "Add demo test file"
          
          # Check if there is anything to commit
          git status
          
          git push origin demo-test-branch

      # Create Pull Request from the new branch to master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Add demo test file"
          body: "This is a test PR with a demo file"
          head: "demo-test-branch"
          base: "master"
