name: CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 2 * * *'  # Run once per day
  workflow_dispatch:

jobs:
  unciv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Autoupdate

      # Demo Test: Add text file to the repository and push to master
      - name: Create demo test file and commit
        run: |
          echo "This is a demo test for the GitHub Action!" > demo_test.txt
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add demo_test.txt
          git commit -m "Add demo test file"
          git push origin master
