name: Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[Auto] PR from ${GITHUB_REF_NAME}'
          body: |
            This PR was automatically created by GitHub Actions.
            It contains changes from the branch: ${GITHUB_REF_NAME}
          labels: automated
          branch: develop
          draft: false
