name: Create Automated PR
on:
  push:
    branches:
      - gbhj # Triggers on any branch starting with 'feature/'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # You might want to add your build/test steps here
      # - name: Run tests
      #   run: |
      #     npm install
      #     npm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated PR from feature branch'
          body: |
            This PR was automatically created by a GitHub Action.
            
            Changes included in this PR:
            - Please review the changes and provide feedback
          base: master  # The branch you want to merge into
          branch: automated-pr  # The branch name for this PR
          delete-branch: true  # Delete the branch after merging
          draft: false  # Set to true if you want to create draft PRs
