name: PR Maintainer Checklist

on:
  pull_request:
    types: [opened]

jobs:
  add_pr_checklist:
    runs-on: ubuntu-latest
    name: Add PR Maintainer Checklist
    permissions:
      pull-requests: write  # This ensures the job can write to PR comments

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR author's pull request count
        id: pr_count
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              head: `${context.repo.owner}:${context.payload.pull_request.head.ref}`
            });
            const prCount = pullRequests.length;
            console.log(`PR count: ${prCount}`);
            return { result: prCount };  # Return result as an object

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Thank you for the pull request!

            This is PR number ${{ steps.pr_count.outputs.result }} from @${{ github.event.pull_request.user.login }} in this repository.

           