name: pr_maintainer_checklist
on:
  pull_request_target:
    branches:
      - master
    types:
      - opened

jobs:
  add_pr_checklist:
    runs-on: ubuntu-latest
    name: Add PR Maintainer Checklist
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if this is the user's first PR
        id: first_interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Thank you for opening this PR! The Scribe team will address your contribution soon."

      - name: Comment PR (First PR)
        if: steps.first_interaction.outputs.first_pr == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for the pull request!
            
            ### Maintainer checklist

            - [ ] The commit messages for the remote branch should be checked to make sure the contributor's email is set up correctly so that they receive credit for their contribution
              - The contributor's name and icon in remote commits should be the same as what appears in the PR
              - If there's a mismatch, the contributor needs to make sure that the [email they use for GitHub](https://github.com/settings/emails) matches what they have for `git config user.email` in their local Scribe-Data repo

            - [ ] The linting and formatting workflow within the [PR checks](https://github.com/scribe-org/Scribe-Data/pull/${{ github.event.pull_request.number }}/checks) do not indicate new errors in the files changed

            - [ ] The [CHANGELOG](https://github.com/scribe-org/Scribe-Data/blob/main/CHANGELOG.md) has been updated with a description of the changes for the upcoming release and the corresponding issue (if necessary)

      - name: Comment PR (Not First PR)
        if: steps.first_interaction.outputs.first_pr == 'false'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for the pull request!

            ### Maintainer checklist

            - [ ] The linting and formatting workflow within the [PR checks](https://github.com/scribe-org/Scribe-Data/pull/${{ github.event.pull_request.number }}/checks) do not indicate new errors in the files changed

            - [ ] The [CHANGELOG](https://github.com/scribe-org/Scribe-Data/blob/main/CHANGELOG.md) has been updated with a description of the changes for the upcoming release and the corresponding issue (if necessary)
